baseURL = 'https://PulseKim.github.io/'
languageCode = 'en-us'
title = "Sunwoo Pulse Kim"
theme = 'hugo-casper3'
[pagination]
  pagerSize = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"


[params]
  github = "https://github.com/PulseKim"
  description = ""
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
  	identifier = "publication"
  	name = "Publications"
  	url = "/tags/publications/"
  	weight = 11
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/PulseKim/"
    weight = 30
  [[menu.main]]
    identifier = "CV"
    name = "CV"
    url = "/files/sunwoocv_241006.pdf"
    weight = 40
  [[menu.main]]
    identifier = "drawing"
    name = "Drawing"
    url = "/pages/"
    weight = 50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
